version: "2"
services:
  web:
    restart: always
    volumes:
      - "./app:/src/app"
    image: 103274529779.dkr.ecr.us-east-2.amazonaws.com/service-database:latest
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
      NODE_ENV: production
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - ./data:/data/db